---
abstract: 'Create CPAN::Mini mirror with recent developer releases'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  File::Find: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200001, CPAN::Meta::Converter version 2.102400'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Mini-Devel-Recent
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  CPAN::Mini::Devel::Recent:
    file: lib/CPAN/Mini/Devel/Recent.pm
    version: 0.06
requires:
  CPAN: 1.92
  CPAN::HandleConfig: 0
  CPAN::Mini: 0.567
  CPAN::Tarzip: 0
  Config: 0
  File::Basename: 0
  File::Path: 0
  File::Spec: 3.27
  File::Temp: 0.20
  YAML::Syck: 1.07
  perl: 5.006
resources:
  homepage: http://github.com/dagolden/cpan-mini-devel-recent/tree
  repository: git://github.com/dagolden/cpan-mini-devel-recent.git
version: 0.06
